[versions]
agp = "8.9.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.2.0"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"
navigationFragment = "2.8.5"
navigationUi = "2.8.5"
activity = "1.10.0"
shizukuApi = "12.0.0"
shizukuSdk = "VERSION_NUMBER"
smartSwipeXVersion = "latestVersion"
swipeButton = "0.8.0"

[libraries]
android-smart-swipe-x = { module = "com.billy.android:smart-swipe-x", version.ref = "smartSwipeXVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
shizuku-api = { module = "me.shizuku.android:shizuku-api", version.ref = "shizukuApi" }
shizuku-sdk = { module = "rikka.shizuku:shizuku-sdk", version.ref = "shizukuSdk" }
swipe-button = { module = "com.eba:swipe-button", version.ref = "swipeButton" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

